project:
  type: website

website:
  title: "Aid Worker Safety Analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Slides"

format:
  html:
    theme: cosmo
  revealjs:
    theme: simple
    transition: convex
    slide-number: true
    center: true
    css: custom.css
